approve deny request
gabrielbursztein/FirstProject pull request #10
Opened 2017-04-17 17:12 UTC by gabrielbursztein

Now its possible to approve and deny requests in de active admin.

2017-04-17 17:29 UTC, MaicolBen requested changes
You opted for doing the actions in the requests controller, but you can do it in the same active admin file with [member actions](https://activeadmin.info/8-custom-actions.html)

2017-04-17 17:29 UTC, MaicolBen commented on app/admin/admin_user.rb
> +    f.inputs "Admin Details" do
Use single quotes

2017-04-17 17:29 UTC, MaicolBen commented on app/admin/book.rb
> +# See permitted parameters documentation:
Remove commented code

2017-04-17 17:29 UTC, MaicolBen commented on app/admin/request.rb
> +# See permitted parameters documentation:
Same as above

2017-04-17 17:29 UTC, MaicolBen commented on app/controllers/requests_controller.rb
> +    request.status = "approved"
You can write this as `request.approved!` (enums creates that method for you), it saves, so there is no need for the line below

2017-04-17 17:29 UTC, MaicolBen commented on app/controllers/requests_controller.rb
> +    request.status = "denied"
Same as above, but with `request. denied!`

2017-04-17 17:29 UTC, MaicolBen commented on app/admin/request.rb
> +      links << link_to('Approve', approve_request_path(request.id), method: :put) if request.status == "pending"
Use single quotes

2017-04-17 17:29 UTC, MaicolBen commented on app/admin/request.rb
> +      links << link_to('Deny', deny_request_path(request.id), method: :put) if request.status == "pending"
Same as above

2017-04-17 17:29 UTC, MaicolBen commented on db/migrate/20170413200652_create_active_admin_comments.rb
> +
Remove empty lines

2017-04-17 17:29 UTC, MaicolBen commented on test/models/admin_user_test.rb
> +class AdminUserTest < ActiveSupport::TestCase
Remove this file

2017-04-17 17:29 UTC, MaicolBen commented on test/fixtures/admin_users.yml
> +one: {}
Remove this file

2017-04-18 15:12 UTC, santiagovidal commented on app/controllers/requests_controller.rb
> +    request = Request.find(params[:id])
Move to a helper.

2017-04-18 15:12 UTC, santiagovidal commented on app/controllers/requests_controller.rb
> +    request = Request.find(params[:id])
Same.

2017-04-18 15:18 UTC, GuilleLeopold commented on app/controllers/authors_controller.rb
> +    author = Author.create(params.require(:author).permit(:name))
Just a comment. I think that it could be a good idea to move `params.require(:author).permit(:name)` to a private method called author_params and then change this line into `Author.create(author_params)`, you don't need to assign this to author

2017-04-18 15:32 UTC, santiagovidal requested changes
Add `public/uploads` to gitignore and refresh the cache.

2017-04-18 15:32 UTC, santiagovidal commented on app/assets/stylesheets/authors.scss
> +// Place all the styles related to the Authors controller here.
Delete this file.

2017-04-18 15:32 UTC, santiagovidal commented on app/controllers/authors_controller.rb
> +    private
You have `private` twice.

2017-04-18 15:32 UTC, santiagovidal commented on app/helpers/authors_helper.rb
> +module AuthorsHelper
Delete this file.

2017-04-18 15:32 UTC, santiagovidal commented on config/routes.rb
> +    resources :authors
For `requests` and `authors` declare only the routes you use.

2017-04-18 16:34 UTC, santiagovidal approved these changes

2017-04-18 16:34 UTC, merged