css books on shelf
gabrielbursztein/FirstProject pull request #7
Opened 2017-04-11 15:45 UTC by gabrielbursztein

Css in Books on my shelf.

2017-04-11 16:10 UTC, GuilleLeopold commented on app/controllers/requests_controller.rb
> +    if user_signed_in?
You can write this if sentence in one line: 
`user_signed_in? ? @requests = current_user.requests : redirect_to new_user_session_path`

2017-04-11 16:13 UTC, GuilleLeopold commented on app/views/books/index.html.erb
> +              <%= link_to 'Request', requests_path(:book_id => book.id), method: :post, remote: true, class: "bold underlined" %>
`:book_id => book.id `syntax is deprecated, use the new syntax: `book_id: book.id`

2017-04-11 16:15 UTC, GuilleLeopold reviewed
Same as the PR before. I don't know if @MaicolBen can check the css, if not, add Ale or Alexis as a reviewer.

2017-04-12 14:07 UTC, MaicolBen commented on app/assets/stylesheets/application.css
> +.wrapper {
Don't put code here, move it to another file

2017-04-12 14:07 UTC, MaicolBen commented on app/assets/stylesheets/application.css
> +  font-family: "Times New Roman";
Use font variable that is already defined

2017-04-12 14:26 UTC, MaicolBen requested changes
Add `db/development.sqlite3` to the git ignore

2017-04-12 14:26 UTC, MaicolBen commented on app/assets/stylesheets/application.scss
> +
Remove empty lines

2017-04-12 16:01 UTC, MaicolBen approved these changes

2017-04-12 16:01 UTC, merged