css in sign in and sign up
gabrielbursztein/FirstProject pull request #8
Opened 2017-04-12 17:59 UTC by gabrielbursztein

Now its not possible to access books index without being logged.

2017-04-13 12:11 UTC, GuilleLeopold commented on config/routes.rb
> +    resources :comments, only: [:create]
As comments is nested inside books, this line should be indented two spaces

2017-04-13 12:19 UTC, GuilleLeopold commented on app/controllers/application_controller.rb
> +  end
Fix indent

2017-04-13 12:22 UTC, GuilleLeopold commented on app/views/devise/sessions/new.html.erb
> +    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
I'm not sure about how necessary are this checks, same above

2017-04-17 17:46 UTC, santiagovidal requested changes

2017-04-17 17:46 UTC, santiagovidal commented on app/controllers/books_controller.rb
> +      user_signed_in? ? @books = Book.all : (redirect_to new_user_session_path)
Check devise's documentation. It provides a helper to ensure authentication.

2017-04-17 17:46 UTC, santiagovidal commented on app/views/devise/registrations/new.html.erb
> +    <div>
You should unindent this `div` because it is outside the form

2017-04-17 17:46 UTC, santiagovidal commented on app/views/devise/sessions/new.html.erb
> +      <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
Why are you adding this?

2017-04-17 19:36 UTC, santiagovidal approved these changes

2017-04-17 19:36 UTC, merged